### PR TITLE
#1123

### PR DESCRIPTION
**Pull request by lc-thomasberger**
Resize plp-indicator to make space for other icons in the navbar.

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
argh sorry I could have sworn I created a branch for my changes!!!

**Comment by moloko** [comment]
sorry about that, this should be back the way it was now.

**Pull request merged**
