### PR TITLE
Fixes #75 -- adds check on _globals

### LINKED ISSUE #75: Defensive programming required on _globals check
In js/PageLevelProgressNavigationView.js code will currently throw an error if the _globals property is missing from course.json.

### PR DESCRIPTION
**Pull request by brian-learningpool**
Without this the code would fail with the following error:
Uncaught TypeError: Cannot read property '_extensions' of undefined

### CODE REVIEW

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
needed in develop as well by the looks of it

**Pull request merged**
