### PR TITLE
Fix: calculation leads to runtime error when switching to structurally different language (fixes #235)

### LINKED ISSUE #235: Calculation leads to runtime error when switching to structurally different language
If the user switches to a structurally different language it is possible for a runtime error to occur. The error will occur in the following scenario:

1. the user opens a page in a particular language
2. whilst on the page the user switches to a language that does not have the page

The [cause ](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/master/js/adapt-contrib-pageLevelProgress.js#L67) appears to be down to the plugin using the current location identifier to locate the page model. As the page model does not exist a reference error occurs.

### PR DESCRIPTION
**Pull request by chris-steele**
#235 

### Fix
* calculation leads to runtime error when switching to structurally different language

### CODE REVIEW

**Comment by oliverfoster** [comment]
This needs more investigation. 

https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/9c6ec1584d965bdf8517ad3699b043d5812a8a01/js/adapt-contrib-pageLevelProgress.js#L35-L38

https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/9c6ec1584d965bdf8517ad3699b043d5812a8a01/js/adapt-contrib-pageLevelProgress.js#L61-L65

It should not be listening to models that don't exist. Could you please find out why a page that shouldn't exist is posting completion events please?

**Comment by chris-steele** [comment]
> Why has the location not been changed when navigating to a new language?
> 
> https://github.com/adaptlearning/adapt-contrib-core/blob/4f04cc88b00570c0b950528d45adb6d60030e144/js/router.js#L364 https://github.com/adaptlearning/adapt-contrib-core/blob/4f04cc88b00570c0b950528d45adb6d60030e144/js/router.js#L204

PLP is responding to a (bubbling) completion property change which occurs during the data load that changing language initiates - this occurs before `adapt:start` triggers routing in the start controller: https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/startController.js#L93

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
Should probably reset the location currentId on language change such that the first if statement returns early?

**Comment by chris-steele** [comment]
This PR will not be necessary if https://github.com/adaptlearning/adapt-contrib-core/pull/567 is approved

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-core/pull/567 is merged

**Pull request closed without merging**
