### PR TITLE
Fix menu PLP progress bar when returning to menu on LMS

### PR DESCRIPTION
**Pull request by jamieshepherd**
There's a problem on the current develop branch when running the framework on an LMS, as the contentObject completion percent doesn't persist across sessions. Instead, it's calculated when you enter a page.

This means that you can complete a contentObject or article, return to the menu and your progress bar will be 100%. However, if you then leave the course, the LMS saves the data, and you then return - the progress bar will be 0% or empty. Only by re-entering the contentObject or article, and then returning to the menu again, will the progress bar return to 100%. Obviously this could result in some confusion with clients returning to a module and thinking their progress hasn't been saved (when in fact, the component completion itself has been).

My fix is simply calculating the progress percentage when the menu is loaded, whether it's been set or not. There might be a more elegant way to do this, or some helper function that makes it more concise, so I'm open to suggestions.

### CODE REVIEW

**Comment by jamieshepherd** [comment]
I've made the PR more concise, used an existing function in the PLP javascript, and it no longer throws undefined error if a component isEnabled is null.

**Comment by oliverfoster** [comment]
Hi Jamie,

We're just about to implement the attribute _isOptional, which will change the way completion calculations occur. Rather than having the completion calculation moved from the core framework into PLP, could you make a fix in the original framework function so that there are less parts to completion calculation to go wrong?

https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/models/contentObjectModel.js#L14 <

**Comment by jamieshepherd** [comment]
Hi Olly. Might need a bit of direction here. I put it in the PLP because a function already existed for it here: https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/develop/js/adapt-contrib-pageLevelProgress.js#L23 and logic already existed for checking sub-menus here: https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/develop/js/adapt-contrib-pageLevelProgress.js#L62

I had seen the getCompleteComponentsAsPercentage function in contentObjectModel, but I'm not sure changing anything here will help, as the PLP is still not calculated until a contentObject has been entered. It's not so much the calculation that's the problem, but when the calculation happens. Happy to change whatever you advise.

**Comment by oliverfoster** [comment]
Looking at the problem I can see I've made a few too many assumptions. getCompleteComponentsAsPercentage doesn't seem to be used anywhere. 

The LMS completion calculations and the PLP completion calculations are independent of one another for the moment (which is good) and the PLP seems entirely in-charge of displaying completion status in page and on menu. Your solution is the best and most consistent approach.

+1

**Comment by belal-almassri-spongeuk** [comment]
+1 Tested and working.

**Comment by moloko** [comment]
one small point - I don't think the comments really add anything, it's pretty clear from the code what the intent is.
also, nice use of the bitwise OR operator on line 54 - hadn't seen that before and it's something I shall be using a lot from now on!

**Comment by zenduo** [comment]
Im not sure this is working 100%, if you go to #/id/co-15 complete all but 1 block, return to the menu for this article, the progress shows 100%, however its not actually completed it should show 80% (or something similar). Please let me know if this is unclear.

**Comment by jamieshepherd** [comment]
I've just pushed a fix for that, I wasn't checking for isEnabled components (therefore some blank components were counting as complete, and you'd get a componentsCompleted + 1 problem), I've now rectified that with some help from @oliverfoster. Open to comments if there's alternative ways of achieving the same thing. Also have removed comments as requested.

Have tested this solution on SCORM cloud which works as expected.

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
Almost there!!

There is on other issue, if a content object holds 2 content objects, the parent content object loses the percentage on closing and resuming of the course. All other issues appear fixed.

To see the latest bug perform the following test:

Enter the "Want to know more about our components" section.
Complete both sections here, return to main menu. Notice "Want to know more about our components" is at 100%, close module then reload. "Want to know more about our components" shows 0%, however clicking in to this section and back out again takes it back to 100%.

**Comment by jamieshepherd** [comment]
I think this issue happened before my fix in the latest develop branch, but should be fixable in a similar way. I'll get on to it when I can.

**Comment by oliverfoster** [comment]
how's this going jamie?

**Comment by jamieshepherd** [comment]
Sorry I've been very busy, going to take a look at it this afternoon.

**Comment by oliverfoster** [comment]
it's alright, i've got 15 tickets to do, 4 of them are plp, so there's no rush.

**Comment by oliverfoster** [comment]
+1 lovely

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
Was the bower.json deleted by accident?

**Comment by oliverfoster** [comment]
yes

**Comment by jamieshepherd** [comment]
Sorry, misunderstanding. Have added it back now.

**Comment by oliverfoster** [comment]
+1

**Comment by taylortom** [comment]
Thanks @jamieshepherd :) +1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
