### PR TITLE
Feature/page completion

### PR DESCRIPTION
**Pull request by oliverfoster**
Introduce control to stop page level progress representing page completion in progress bars.

```
_pageLevelProgress: {
   _showPageCompletion: false
}
```

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
Yes. If you set it to _showPageCompletion: false. It's on by default.

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by dancgray** [comment]
@oliverfoster, quite an old PR but I think it is still very useful. Sorry I missed in back in Nov.

**Comment by oliverfoster** [comment]
It's alright, it's one of those PRS you won't know you'll need until you want to so something a bit odd. I want to use it for a revision mode whereby only the reset components need to show in the plp. It think we've had only a couple of use cases so far.

**Comment by hrajotia** [comment]
+1

**Pull request merged**
