### PR TITLE
ABU-1097: Added Menu PLP Aria Label

### PR DESCRIPTION
**Pull request by oliverfoster**
change to use new aria label https://github.com/adaptlearning/adapt_framework/pull/786

### CODE REVIEW

**Comment by dancgray** [comment]
+1, needs adding to the properties.schema and framework course.json i guess?

**Comment by oliverfoster** [comment]
it's in the course json already on that pr in the comment^, and the defensive code is in to prevent error if it's not there.

yea, schema will need updating. two ticks.

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
