### PR TITLE
Accessibility fix. https://adaptlearning.atlassian.net/browse/ABU-867

### PR DESCRIPTION
**Pull request by chris-steele**

### CODE REVIEW

**Comment by oliverfoster** [comment]
@chris-steele could you change all PLP related references from:
```
{{_globals._accessibility._ariaLabels. 
```
to
```
{{_globals._extensions._pageLevelProgress
```

complete, incomplete etc can stay as they are, as they're more generic

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by dancgray** [comment]
@chris-steele any chance you could apply the changes @oliverfoster has asked for this morning

**Comment by dancgray** [comment]
See https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/62

**Pull request closed without merging**
