### PR TITLE
add 'translatable' property

### PR DESCRIPTION
**Pull request by moloko**
prep for multilanguage support

### CODE REVIEW

**Comment by tomgreenfield** [comment]
Missing one [here](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/85/files#diff-4517165ffe55c65dfed48457eadd2d1cR12)?

**Comment by moloko** [comment]
@tomgreenfield yes - fixed now

**Comment by tomgreenfield** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
